# Background

The vaccines against COVID-19 have been considered a major achievement of modern medicine as their rapid development allowed the start of broad vaccination campaigns towards the end of 2020 in certain countries, such as the US and Canada [@davis2022;@bogoch2022;@tanne2020]. This made some believe that vaccines were destined to be a determinant factor in a rapid ending of the pandemic [@thelancet2021]. However, although it has been estimated that COVID-19 vaccines have prevented around 14 million of deaths worldwide [@watson2022], their implementation has been far from being equal to that of the vaccines of smallpox and polio, which were implemented on a global scale and that were indeed crucial to control these diseases [@kayser2021]. In fact, the rollout of COVID-19 vaccines has faced multiple challenges since its inception which ultimately have hampered their use to achieve the ultimate goal of global immunity.

This problematic of COVID-19 vaccines rollout is a multifaceted issue resulting from, among other things, the development of new variants due to inadequate public health measures [@li2021],  inequality in vaccine access between high- and low-income countries[@gerretsen2021; @tamey2022], vaccine hesitancy[@nafilyan2021], and differences in vaccination uptake across different segments of the population [@malik2020]. In particular, it is well established that differences in vaccination uptake have been present even in countries that have had ample access to vaccines since 2020 (such as the US, the UK, and Canada),  where lower vaccine uptake has been observed  within racial minorities (i.e., individuals that identify as Black, Asian, or Indigenous), and in individuals within low income brackets [@willis2021;@skirrow2022;@stoler2021;@khubchandani2021]. Reasons given for lower vaccine uptake in these cases have included medical mistrust due to systemic medical racism [@stoler2021], mistrust in vaccines [@willis2021], and the influence of conspiracy theories [@bogart2021;@mosby2021;@freeman2020]. Moreover, in the case of Canada, lower vaccine uptake has been observed in young individuals, those with a low educational level, households with children, those without a regular healthcare provider, individuals that identify as part of a visible minorities or Indigenous, and those that are financially unstable [@guay2022;@muhajarine2021;@hussain2022]. 

However, it is important to consider that vaccination uptake can also be influenced by geographical (spatial) factors. 
In this regard, differences in COVID-19 vaccination rates have been associated with varied regional attitudes towards vaccination [@malik2020], spatial differences in vaccine access and supply, vaccination location availability, and lack of prioritization of areas where vulnerable groups reside [@bogoch2022; @nguyen2021]. Other studies have also shown heterogeneity in vaccine uptake within small governmental administrative units such as counties [@mollalo2021; @yang2022; @tiu2022; @bhuiyan2022], and that and that accounting for geographical differences in vaccination can help predict patterns of booster uptake [@wood2022]. Overall, the evidence provided by the literature demonstrates the existence of spatially-driven heterogeneities in vaccine uptake that be used by decision-makers in the development of public health policies that are focused on addressing these disparities within specific administrative or geographical areas. 

However, such analyses have been carried mostly in territories outside of Canada, where available studies have been focused in certain cities (such as Toronto [@choi2021], or Montreal [@mckinnon2021]), or have explored differences at a province-wide level [@guay2022]. Thus, there is a need for studies that explore spatial differences in vaccination within the Canadian territory and that consequently, can help identify disparities that need to be addressed within specific areas in each province.

This need is particularly important in the case of Ontario, the most populated province in Canada. Between 2006 and 2019, Ontario provided healthcare access to its inhabitants using 14 intra-provincial divisions called the Local Health Integrated Networks (LHINs). However, this approach was complex, bureaucratic, and led to systemic inequalities [@tsasis2012]. In late 2019, the 14 LHINs were phased out and the areas they covered were incorporated into 6 Health Regions (North East, North West, Central, Toronto, West, and East) in an effort to improve the healthcare system of the province [@dong2022]. Because the adoption of the Health Regions occurred at a relatively recent time, there is an ongoing need to analyze the impact of this measure and identify the existence of intra-regional differences that might exist, and which could be specially important in the context of the COVID-19 pandemic.

In this study, we analyzed differences in self-reported COVID-19 vaccination status in Ontario using socio-economic (e.g., income, racial/ethnic identification), and spatial  information at the level of the Health Regions to identify the existence of differences that might need to be addressed to ensure that the healthcare system of Ontario is more inclusive and that responds to the needs of its most vulnerable population.
