# Background

The COVID-19 pandemic continues around the world with more than 600 million confirmed cases as of November of 2022 [@WHO-Covid]. During the first months of the pandemic in early 2020, non-pharmaceutical interventions such as masking and social distancing were the only methods available to manage the spread of the disease; however, the rapid development of vaccines permitted their approval and use in some countries towards the last month part of 2020. For example, in the US and Canada vaccine campaigns began in mid-December of 2020 [@tanne2020; @bogoch2022]. Although it has been estimated that COVID-19 vaccines have prevented around 14 millions of deaths worldwide [@watson2022], the rollout of COVID-19 vaccines has faced multiple challenges since its inception.

Indeed, multiple obstacles that have complicated vaccination efforts against COVID-19 have been identified: inequality in vaccine access, vaccine hesitancy, and differences in vaccination rates across different segments of the population [@gerretsen2021; @nafilyan2021; @malik2020]. In the case of Canada, lower vaccine uptake has been associated with socio-economic factors such as younger age, educational level, presence of children in the household, lack of a regular healthcare provider, ethnic origin, and financial instability [@guay2022;@muhajarine2021;@hussain2022].

Additionally, vaccination is influenced by changes in geography. In this regard, it has been shown that there have been spatial differences in COVID-19 vaccination rates due to regional differences in attitudes towards vaccination [@malik2020], geographical differences in vaccine access and supply, vaccination location availability, and lack of prioritization of vulnerable groups [@bogoch2022; @nguyen2021].

Studies that analyze geographical variations in vaccine uptake are important as they can help inform public health decision-makers to design policies to that consider spatial changes to address vaccination disparities. In this regard, previous geographical (spatial) analyses of vaccination rates have shown that variations in vaccine uptake can occur within small governmental administrative units (e.g., counties in the case of the US) [@mollalo2021; @yang2022; @tiu2022; @bhuiyan2022], and that geographical analyses can be predictive of booster uptake patterns [@wood2022].

In Canada, studies that have used a spatial approach to analyze vaccine uptake have shown disparities in vaccination rates across low and high income neighborhoods in the city of Toronto [@choi2021], among adolescents from deprived neighborhoods in the city of Montreal [@mckinnon2021], and have also highlighted disparities in vaccination status depending on age, income, and ethnic origin at the provincial level [@guay2022]. However, there is limited information on differences in vaccination status inside the provinces. Such analysis is important as it can help identify inequalities that may exist within these geographical areas while providing a granular view of intra-provincial differences that can help understand the barriers for vaccine uptake. 

In this study, we examined self-reported COVID-19 vaccination status within the province of Ontario using a combination of socio-economic factors(such as ethnic origin, age, and income) and geographical analysis (at the level of the Health Regions) in order to determine intra-provincial differences in vaccine uptake and address the ongoing need of socio-economic information that can provide a rationale for the disparities in vaccination observed within some racial groups [@cnat2022b].