# Methods

## Data source: survey overview

We used data from the *Survey of COVID-19 related Behaviours and Attitudes*, a repeated cross sectional survey focused on the Canadian province of Ontario which ran from Sept 30, 2021 until January 17, 2022 and that was comissioned by the Fields Institute for Research in Mathematical Sciences (henceforth Fields) and the  Mathematical Modelling of COVID-19 Task Force.  The survey was conducted by a third-party service provider (RIWI Corp.), under ethical guidance from the University of Toronto.

Briefly, the survey was deployed used random domain intercept technology, where if users clicked on a registered but commercially inactive web link or typed in a web address for a site that was dormant, they had a random chance of that link being temporarily managed by the company that administered the survey and instead of coming across a notification about the status of the site("this page does not exist"), the survey was deployed to the user [@sargent2022]. Users then decided whether to anonymously participate, and those that participated were able to exit the survey at any time. After the survey closed, regardless if it was complete or incomplete, access was denied to any further users with the same internet protocol (IP) address and the domain entry point rotated such that if a user were to attempt to access the survey again, share the link, or enter via the same address using an alternative IP address, the survey would not deploy. This effectively meant that a user could participate only once in the survey.

Additionally, users who indicated they were under the age of 16 were exited from the survey, no record was created, and these users were unable to navigate back to the "age select" screen. The personal identifier information from each user was automatically scrubbed and replaced by a unique ID. Respondents were drawn exclusively from the province of Ontario, as per their devices meta-data.

## Survey responses

### Socio-demographic factors {#sec-socio-demographic-factors}

Socio-economic information selected for analysis from the survey answers included age group, income bracket, and race/ethnicity. Information about these socio-economic factors in the survey is provided in @tbl-covariates.

| Variable             | Values                                                                                                                          |
|:------------------|-----------------------------------------------------|
| Age group            | 16-24,25-34,35-44,45-54,55-64, 65+                                                                                              |
| Income bracket (CAD) | \<15,000, 15,000-24,999, 25,000-39,999, 40,000-59,999, 60,000-89,999, \>90,000                                                  |
| Race/ethnicity       | Arab/Middle Eastern, Black, East Asian/Pacific Islander, Indigenous, Latin American, Mixed, South Asian, White Caucasian, Other |
|                      |                                                                                                                                 |

: Selected socio-economic factors from the survey {#tbl-covariates}

Furthermore, the information on vaccination status was provided by survey participants who answered the question "Have you received the first dose of the COVID vaccine?", with possible answers "yes" and "no". 

<!-- -   (If answered "yes" to the previous question) "Have you received the second dose of the COVID vaccine?" with possible answers "yes" and "no" -->

<!-- -   (If answer was "no" to the first question) "If a vaccine was made available to you you would:" with possible answers "definitely get", "definitely not get", "probably get", and "probably not get" -->

<!--           - definitely get -->

<!--           - definitely not get -->

<!--           - probably get -->

<!--           - probably not get -->

## Data cleaning

The original dataset contained 39,029 entries (where each entry corresponded to a set of answers provided by a unique respondent). Following a preliminary analysis, the dataset was cleaned in order to only contain the socio-economic information provided in @tbl-covariates and vaccination status. The cleaning process also included removing outliers that were identified during the preliminary analyses. Specifically, we removed those respondents that indicated to be below 25 years of age, living in a household of size 1, and that reported an income above CAD 110,000. The next step consisted in processing the geographical information in the survey (city where the survey was responded) in order to match each city to its correspondent Health Region. Details of this process are given below.



### Geographical location {#sec-geographical-location}

For each survey participant certain data was automatically captured, including the nearest municipality (city). This resulted in a total of 578 different municipalities within the clean dataset. Due to our interest in analyzing the differences between Health Regions, we assigned the city of each entry to its correspondent Health Region following a multi-step process. Briefly, we used Local Health Integrated Networks (LHINs) to assign a Health Region to each entry in the survey. LHINs were the geographical divisions for health used by  Ontario before the adoption of the Health Regions; because of the lack of a publicly available list of all municipalities within each Health Region, we used a dataset of long-term care homes and LHINs to match each city to LHIN, followed by matching each LHIN to a Health Region following the information provided on the Ontario Health Website, where the list of LHINs and corresponding Health Regions is available. In the case of municipalities that did not appear in the long-term dataset, we manually searched each city in the LHINs websites in order to provide geographical information. The raw dataset, clean dataset, details of the data cleaning process, and the addition of Health Region and LHIN information are described in detail in the github repository: https://github.com/aimundo/Fields_COVID-19/.

Following an assessment of the number of entries corresponding to each Health Region in the final dataset, only 107 observations (4.3% of the total) corresponded to cities located in the North West and North East Health Regions. Due to the low number of entries, we omitted these Health Regions from further analyses. Therefore, the total number of unique entries used for analysis was 3,551 which included the East, Central, Toronto, and West Health Regions.

## Corrections

We identified differences between the proportions of all the socio-economic factors included in the analysis (@tbl-covariates) and the 2016 Canada Census data for Ontario. Additionally, because the Census divisions do not match the exact boundaries of the Health Regions, we also obtained population estimates for each Health Region from the Ontario Health website in order to correct for the population totals. We used an iterative proportional fitting procedure (_raking_) [@deming1940] to correct for socio-economic factors and Health Region populations using the R `survey` package. Details about the correction can be found in the Appendix.

## Statistical analyses

We used a fixed-effects logistic regression model to estimate the probability of vaccination depending on the socio-economic factors described in @sec-socio-demographic-factors and the Health Regions from @sec-geographical-location, as previous studies have shown that socio-economic factors and their interactions are significant predictors of intent of vaccination and vaccination status [@nguyen2022; @shih2021; @cnat2022a]. The model appears in @eq-model3,

$$
\begin{aligned}
\log \left( \frac{p\textrm{(vac)}}{1-p\textrm{(vac)}} \right) = \beta_0+ \beta_{1}\textrm{(Age group)} +\beta_{2} \textrm{ Race} + \beta_3 \textrm{ Health Region} + \beta_4 \textrm{ Income}+\\ \beta_5\textrm{(Health Region} \times \textrm{Income)} + \beta_6 \textrm{ (Age group} \times \textrm{Income)} + \beta_7 \textrm{ (Race} \times \textrm{Income)}
\end{aligned}
$$ {#eq-model3}

Where $p\textrm{(vac)}$ indicates the probability of having received the first dose of a Covid-19 vaccine, $\beta_0$ indicates the population intercept, $\beta_1...\beta_7$ indicate the coefficients for each of the fixed and interaction effects of age group, race, Health Region, and income. The the model was fitted using the function `svyglm` from the `survey` R package in order to incorporate the correction in sampling probability obtained from raking.

All analyses were conducted in RStudio (2022.12.0 Build 353), using R 4.2.2 and the packages `survey` [@lumley2011],`tidyverse` [@wickham2019], and `quarto` [@quarto].

