# Discussion

The rapid development of COVID-19 vaccines has been considered as a major achievement of modern medicine [@davis2022]. Vaccine availability towards the end of 2020 in certain countries made some believe that they would be a determinant factor in a rapid ending of the pandemic [@thelancet2021]. However, despite previous successful vaccination campaigns that were crucial to control diseases such as smallpox and polio [@kayser2021], vaccination efforts in the case of COVID-19 have faced multiple challenges that have complicated the achievement of global immunity.

Among the different challenges faced by COVID-19 vaccination efforts are the development of new variants due to inadequate public health measures [@li2021] and inequity in vaccine access between low and high income countries [@tamey2022]. However, it is also well established that even in the case of high income countries that have had ample access to vaccines since 2020, such as the US, the UK, and Canada, there have been challenges in vaccination efforts due to differences in vaccine uptake among different segments of the population. More specifically, lower vaccine uptake has been associated with socio-economic factors such as race (i.e., identifying as Black, Asian, Indigenous) and household income (typically within lower income brackets) [@willis2021;@skirrow2022;@stoler2021;@khubchandani2021]. Reasons given for this association have included medical mistrust due to systemic medical racism, mistrust in vaccines, and the influence of conspiracy theories [@stoler2021;@willis2021;@bogart2021;@mosby2021;@freeman2020].

In addition, vaccine uptake is influenced by geography, as shown by different studies that have identified intra-regional differences in vaccine uptake [@pallathadka2022;@huang2022;@mollalo2021]. However, in the case of Canada, studies that have analyzed spatial differences in vaccination have been focused in country-wide or province-wide estimates [@lavoie2022;@guay2022]. Therefore, we explored spatial and socio-economic determinants of vaccination status in the province of Ontario. This province is of particular interest as it has seen recently major structural health changes with the dissolution of the Local Health Integrated Network (LHIN) system and the incorporation of regions covered by LHINs into larger Health Regions [@dong2022]. Because the idea behind the change aimed to reduce the inequalities in healthcare that were identified under the LHIN model [@tsasis2012], examining differences in vaccination between the Health Regions can provide decision-makers with insight regarding intra-provincial health disparities that may need to be addressed in future vaccination or public health campaigns.

Our results indicate that across the most densely populated Health Regions of Ontario, almost three quarters of the surveyed individuals reported having received the first dose of the COVID-19 vaccine (@tbl-descriptive-stats), and that there were no significant differences in vaccination odds among the age groups considered in the survey. This result is consistent with overall vaccination rates reported for Canada, which have been relatively higher when compared to other high income countries [@dube2022], with vaccination uptake rates across different age groups presented in other studies [@macdonald2021;@guay2022], and with the vaccination information provided by Public Health Ontario,  which shows that for the period where the Fields survey ran (Sept 30, 2021-Jan 17, 2022) there was a minimum of  80% of first dose vaccination coverage among all the age groups considered in the survey [@ontario-covid].

However, we identified intra-provincial differences in vaccination based on socio-economic and geographical factors. First, our results show significant differences in vaccination odds in individuals with a household income below CAD 60,000 and in individuals belonging to visible minority groups. Those who identified as Black, Latin American, or  belonging to a minority group not included in the survey (Southeast Asian, Filipino, West Asian, and Minority not identified elsewhere) had vaccination odds below 33% when compared to individuals that identified as White/Caucasian (@tbl-model). These results are consistent with other studies that have shown lower vaccination rates in individuals that identify as part of a racial minority, or that have a low household income [@guay2022;@muhajarine2021;@carter2022;@hussain2022].

In this study, we also decided to explore the interactions between income and race and race and Health Region, as it is known that many individuals within racial minority groups perform tend to occupy certain types of occupations that fall within income brackets that have been shown to be associated with differences in vaccination uptake. In other words, we decided to explore if there were differences in vaccination within racial groups in certain income brackets and in certain the Health Regions. In this regard, it is interesting to note that although overall self-reported vaccination rates were found to be statistically significantly lower in various racial minority groups when compared to White/Caucasian individuals (@tbl-model), the change in odds of vaccination within certain racial groups and income strata was actually positive, in contrast to the White/Caucasian group, for which vaccination odds decreased in lower income brackets (when compared to the CAD 60,000 and over bracket, Supplementary Figure A-3). More specifically, the change in odds of vaccination increased in individuals who identified as Arab/Middle Eastern, Black, Latin American, or belonging to other minority groups with a household income below CAD 25,000, which was also true for individuals in other racial minority groups with an income between CAD 25,000-59,999 (@tbl-model, Supplementary Figure A-3).

This result is likely due to the fact that individuals that belong racial minority groups tend to perform occupations that have been deemed as "essential" in the context of the pandemic [@hawkins2020;@ct2021], which include occupations such as grocery store workers, gas station workers, warehouse and distribution workers, and manufacturing workers, all being occupations for which an income within the significant brackets is to be expected.  In the case of Ontario, essential workers had priority for COVID-19 vaccination [@mishra2021], which would explain the higher odds of vaccination for these individuals in certain income brackets, in contrast to the lower odds of vaccination for the same type of individuals with higher household income. In other words, it is possible that the type of occupation played an important role in increasing the odds of vaccination in these racial minority groups.

Additionally, significant higher vaccination odds were identified in the West Health Region when compared to the Health Region of Toronto (@tbl-model). The West Health Region comprises the regions of Waterloo and Niagara, the counties of Wellington, Essex and Lambton, and the cities of Hamilton, Haldimand, Brant, and Chatham-Kent. In this case, a possible rationale for the results is the fact that in the survey, about 47% of the entries for this Health Region corresponded to White/Caucasian individuals, who reported an overall 83% vaccination rate (Supplementary Table A-6). However, the interaction effect of Health Region and race was also significant in the case of individuals identifying as South Asian or other minorities not included in the survey [@tbl-model]. In this case, the results of the interaction term in the model indicate that the odds of vaccination for those within the South Asian and Other minority groups in the West Region decreased when compared to the other Health Regions (Supplementary Figure A-4).

According to Ontario Health, 13.2% of the population in the West Health Region identifies as a visible minority, whereas 2.5% identifies as Indigenous [@ontariohealth]. In the case of this analysis, the estimated lower odds are likely to be explained from a socio-economic perspective. In fact, 50% of the answers from this region in the survey came from the former LHINs of Hamilton Niagara Haldimand Brant, and Erie St. Clair, both which are among the regions of Ontario with the highest proportion of their population (more than 20%) in the lowest income quintile [@buajitti2018] (Supplementary Table A-7). Therefore, this result partly reinforces the well-known existing association between low vaccination rates and income, but it additionally indicates that there were intra-regional differences in vaccination. Interestingly, a disproportionate number of COVID-19 cases and low vaccination rate (under 50%) have been previously reported in the South Asian community of Ontario [@anand2022]; in this regard, our result provides additional context  by showing that within the South Asian community, there were differences in vaccination uptake across Ontario. Moreover, because significant lower odds of vaccination were also identified  other minority groups, this provides a rationale for future studies that explore how vaccination uptake varies across different minority groups within Ontario and other Canadian provinces.

There are some limitations to the present study. First, the data collection design, which allowed respondents to withdraw from the survey at any point, resulted in a high number of unique entries in the survey with multiple missing answers. Because we focused on entries that had complete observations in the covariates of interest for our analysis, it is possible that some information was not considered by excluding observations that had information in other variables (such as work from home, or number of persons in the household). However, we attempted to minimize this possibility by correcting the dataset using information from the Census. More granular corrections, which for example could be based on demographic information by municipality, could be used in the future to obtain a more accurate approximation to the population totals of the province. Additionally, the results in this study are based on self-reported data, where the risk of bias exist. Despite this, because in the context of COVID-19 it has been shown that good agreement exists between self-reported and documented vaccination status [@stephenson2022], the effect of self-reported bias is likely to not be significant in this case.

Finally, it is likely that there have been differences in vaccination across the province as more doses of the vaccine were administered and as successive variants emerged. Because this study focused only on vaccination status regarding the first dose of the vaccine within a relatively short time window, it can only provide a snapshot of the societal dynamics behind the pandemic. Nonetheless, the results presented here can serve as a starting point to motivate future longitudinal research that aims to quantify geographical differences within vulnerable segments of the population, and that can be used to inform the development of public health policies within the province of Ontario or across other provinces that aim to minimize disparities in health access.
