# Conclusion

The implementation of the Health Regions in Ontario aimed at reducing the bureaucratic complexity and health disparities identified under the LHIN model. However, there are certain challenges that this new model will need to overcome in order to work syngergistically with the rest of the healthcare system of the province. First, each Health Region now covers a large geographical area that was served in the past by multiple LHINs. This in turn creates a complex socio-demographic landscape within each Health Region that is likely to be different in each case due the different levels of rurality and the proportion of underrepresented groups in each Health Region. 

Second, it is likely that a future pandemic or public health emergency will impact the province in the years ahead. Although broadly speaking, PHO and OH have been able to collaborate on the COVID-19 vaccination rollout, future events will require a unified response from both the public health arm of the government (represented by PHO), and the healthcare system agency (OH). So far, the COVID-19 pandemic has served as a stress test for both agencies, showing the necessity from decision makers to clearly define how PHO and OH will interact in the future in order to ensure that Ontarians can benefit by virtue of a robust collaboration between both agencies. The evidence collected in this study shows that healthcare disparities experienced by underrepresented individuals in the province are the result of complex relationships between infrastructure, resources, occupations, geography, and socio-economic factors, among others. Therefore, this complexity presents an ongoing challenge for the healthcare system of Ontario, which will need to adapt and continue to aim for an integrative approach that can serve those that are most vulnerable.


<!-- So far, the evidence collected during the COVID-19 pandemic indicates that differences in vaccination uptake are associated to a lack of infrastructure and resources that can adequately support personalized care to marginalized individuals. In the near future, health decision-makers will need to consider the implementation of policies that are focused on addressing this problematic. -->

Finally, the recent nature in the adaption of the Health Region poses a challenge for researchers in the acquisition of data and information that can be used to analyze the performance of the new model. From one side, the Health Regions have not been incorporated as part of Census data (LHINs were considered before in the Census), and this impact the amount and level of detail of available information. On the other hand, evaluations of the Health Region model are at the moment not considered in the Annual Reports of the Auditor General of Ontario, which was critical in the past to identify limitations in the LHIN model. Currently, the only demographic information available for each Health Region is provided by Ontario Health (the agency that administers the Health Regions) but this information only provides general estimates that do not allow for detailed analyses of performance indicators (such as hospitalizations, readmissions, and trends in chronic disease incidence) between the Regions. Therefore, there is a pressing need for open data that can be used by researchers and decision-makers to examine the performance of the Health Region model.

The Health Region model will only by successful if it ensures that healthcare improves across all segments of the population of Ontario, particularly in the event of a future public health emergency or pandemic where so far, based on the experience of the COVID-19 pandemic, underrepresented individuals have been disproportionately affected.