# Background

As of May of 2023, there have been 765 million confirmed cases of COVID-19 around the world, including 6.8 million deaths [@WHO-Covid]. Although this disease is no longer categorized as a global health emergency by the World Health Organization (WHO) [@rigby2023], there is ongoing concern due to continued transmission, surges in cases and deaths due to new variants [@un2023], and weaknesses in health systems around the world that could be exploited by a novel virus or another public health emergency in the future [@mackey2021].

In particular, a major weakness that has received attention during the pandemic has been related to vaccination. The rapid development of vaccines against COVID-19 initially brought the hope of a rapid end to the pandemic as vaccination campaigns in certain parts of the world started toward the end of 2020[@thelancet2021;@davis2022;@bogoch2022;@tanne2020]. However, although it has been estimated that COVID-19 vaccines have been able to prevent millions of deaths worldwide [@watson2022], they were ultimately unable to bring the pandemic to a rapid end, in contrast to previous experiences (such as in the case of smallpox), where the global vaccination program was crucial to control this disease[@kayser2021].

This failure of vaccines to stop the pandemic is a complex issue resulting from a combination of factors, among which are inadequate public health measures and the emergence of new variants [@li2021], inequality in vaccine access between high- and low-income countries [@gerretsen2021;@tamey2022], vaccine hesitancy [@nafilyan2021], and differences in vaccine uptake across the population[@willis2021;@skirrow2022]. In particular, it is well established that lower vaccination uptake has been observed in individuals within certain underrepresented groups (e.g., Black, Asian, or Indigenous) as well as individuals with socio-economic disadvantages [@willis2021;@skirrow2022;@stoler2021;@khubchandani2021;@guay2022;@muhajarine2021;@hussain2022]. 

Reasons given for this inequality in vaccination uptake have included medical mistrust due to systemic medical racism [@stoler2021;@mosby2021], mistrust in vaccines [@willis2021], and the influence of conspiracy theories [@bogart2021;@mosby2021;@freeman2020].  However, it is important also to consider that vaccination uptake can be influenced by geographical (spatial) factors. In this regard, differences in COVID-19 vaccination rates have been associated with varied regional attitudes towards vaccination [@malik2020], spatial differences in vaccine access and supply, vaccination location availability, and lack of prioritization of areas where vulnerable groups reside [@bogoch2022; @nguyen2021]. Other studies have also shown heterogeneity in vaccine uptake within small governmental administrative units such as counties [@mollalo2021; @yang2022; @tiu2022; @bhuiyan2022], and that accounting for geographical differences in vaccination can help predict patterns of booster uptake [@wood2022]. 

However, such analyses have been carried out mostly in territories outside of Canada, where available studies have been focused in certain cities (such as Toronto [@choi2021], or Montreal [@mckinnon2021]), or have explored differences at a province-wide level [@guay2022]. Therefore, there is a need for studies that explore spatial differences in vaccination within the Canadian territory and that consequently, can help identify disparities that need to be addressed within specific areas in each province.

This need is especially important in the case of Ontario, the most populated province of Canada. Between 2007 and 2019, Ontario managed healthcare access to its inhabitants using 14 intra-provincial divisions called the Local Health Integration Networks (LHINs), which aimed to provide an integrated health system for the province. However, this approach was complex, bureaucratic, and resulted in excessive expenditures, disparities in mortality rates, the deterioration of certain performance indicators such as wait times and hospital readmissions, fragmented electronic health systems, the decline of performance indicators, and inequities in health services access [@tsasis2012;@muratov2018;@dong2022;@lysyk2015;@lysyk2016]. Therefore, with the intent of better organizing and delivering care in late 2019 the provincial government eliminated the LHINs and incorporated the areas covered by them into six larger Health Regions (North East, North West, Central, Toronto, West, and East) [@dong2022]. 

Because of the relatively recent adoption of the Health Region model and its alignment with the onset of the COVID-19 pandemic, there is a need to analyze if there are ongoing disparities in health access under this approach that need to be addressed before they are exploited by a new disease or public health threat. In this regard, previous research has highlighted disparities in the level of activity of each Health Region [@sethuram2023]. Therefore, analyzing differences in vaccination uptake within the Health Regions and can help identify which socio-demographic groups are the most vulnerable and what areas of the province deserve special attention by decision-makers. 

Therefore, in this study we aim to understand the differences in vaccination uptake between the different Health Regions of Ontario between October of 2021 and January of 2022. By including socio-economic factors in our analysis, we aimed to identify in which groups these differences were significant in order to provide an assessment of the current state of healthcare access in Ontario.
