# Discussion



had significantly higher odds of vaccination than those in the Health Region of Toronto

Between 2007 and 2019, healthcare in Ontario was managed by 14 different LHINs, which aimed to provide an integrated health system for the province. However, this approach faced chronic problems such as fragmented electronic health systems [@lysyk2016], the decline of performance indicators (e.g., increased unplanned emergency visits, number of patient readmissions), and inequities in health services access [@lysyk2015]. Based on these problematics and with the intent of better organizing and delivering care, the provincial government moved to the Health Region model in late 2019 [@dong2022]. 

In this study we hypothesized that differences in COVID-19 vaccination uptake were present between the Health Regions, aiming at determining which socio-demographic groups could be impacted by these disparities in order to provide decision-makers with information that could be used to develop policies focused on reducing or eliminating these differences and ensure that the Health Region model is able to fulfill its missing of improving health access for the inhabitants of Ontario.

Our results show differences in odds of vaccination in individuals across certain socio-demographic groups. Specifically, those who identified as Arab/Middle Eastern, Black, Latin American, having mixed racial or ethnic background, or that belonged to other groups not explicitly included in the survey (Southeast Asian, Filipino, West Asian, and minority groups not identified elsewhere) had vaccination odds that were between a third and a half of that of individuals that identified as White/Caucasian (@fig-models). These results are consistent with previous studies that have shown lower vaccination rates in individuals with the same socio-demographic characteristics [@guay2022;@muhajarine2021;@carter2022;@hussain2022]. 

Lower vaccine uptake in the socio-demographic groups indicated above may be influenced in part, by vaccine hesitancy and refusal, which have been associated in equity-deserving Canadian individuals to concerns on vaccine safety, effectiveness, and experiences of racial discrimination in health settings [@basta2022;@cnat2022a;@cnat2022b;@cnat2023]. However, it has been shown that structural barriers also play an important role in vaccination uptake. In the case of equity-deserving individuals, such barriers include complex scheduling systems, language barriers, lack of adequate public transportation, and lack of accessible vaccination sites [@njoku2021]. In this regard, it is interesting to note that vaccination venues were scarce in low socio-economic areas that had the highest burden of COVID-19 in Toronto and other regions of Ontario around the time covered by the survey [@bogoch2022;@iveniuk2021], and that pharmacies in the Peel region (an area identified as a "hotspot" with high numbers of essential workers and multigenerational households) could not keep up with demand [@gill2022] . However, to the best of our knowledge, there seems to be a very limited amount of studies in this area, indicating an ongoing need of future studies that examine the longitudinal impact of vaccine accessibility and structural barriers that affected equity-deserving groups within the province.

Although overall self-reported vaccination rates were found to be statistically significantly lower in various racial minority groups when compared to White/Caucasian individuals, the change in odds of vaccination within certain racial groups and income strata was actually positive, in contrast to the White/Caucasian group, where vaccination odds decreased in lower income brackets (when compared to the CAD 60,000 and over bracket, Supplementary Figure A-5). Specifically, individuals in low income brackets that belonged to Arab/Middle Eastern, Black, or other minority groups had higher odds of vaccination that their peers with an income above 60,000 CAD.

This result is likely due in part to the fact that individuals that belong racial minority groups tend to perform occupations that have been deemed as "essential" in the context of the pandemic [@hawkins2020;@ct2021], which include grocery store workers, gas station, warehouse, distribution, and manufacturing workers, all being occupations for which an income within the significant brackets identified in the analysis is to be expected. In Ontario, these workers had priority for COVID-19 vaccination [@mishra2021]; and interestingly, there is evidence of interventions by vaccination staff in certain parts of the province to encourage vaccination uptake by these individuals [@gill2022]. These facts, combined with evidence of increased trends in vaccination in this group elsewhere [@nguyen2021b], suggest that the type of occupation from individuals in equity-deserving groups played an important role in increasing the odds of vaccination in the province.

Additionally, the interaction effect of Health Region and race was also significant in the case of individuals identifying as Indigenous or with mixed racial background in the West Health Region, Black individuals in the Central Health Region, and Arab/Middle Eastern individuals in the East Health Region [@fig-models]. In these cases, vaccination odds were lower when compared to those of individuals in the Toronto Health Region (Supplementary Figure A-6). Although these findings are likely the result of multiple causes, we would like to indicate some contributing factors that might help provide context in each case.

To contextualize these results, it is useful to disaggregate by LHINs, because in the literature, most of the studies that have analyzed health in Ontario use the LHINs as the base of their analyses. From this perspective, is interesting to note that most observations corresponding to Indigenous individuals and those with of mixed racial background in the West Health Region came from the Hamilton Niagara Haldimand Brant, South West, and Waterloo Wellington LHINs, whereas for Arab/Middle Eastern Individuals in the East Health Region the LHINs with the highest number of observations corresponded to the Champlain and Central East. Previous research has identified health disparities in these (mostly rural) regions, such as unequal distribution of primary care providers, increased mortality, and low pharmacist availability [@shah2019;@crighton2015;@timony2022].

Furthermore, the socio-demographic composition of the Health Regions is varied. For example, in the West Health Region Indigenous individuals and visible minorities account for 15.5\% of the population, whereas in the Central Health Region these groups account for 48\% of the population. Despite this, it seems that in both regions there continues to exist limitations  are only 3 Aboriginal Health Access Centres [@ontariohealth]

According to Ontario Health, 13.2% of the population in the West Health Region identifies as a visible minority, whereas 2.5% identifies as Indigenous [@ontariohealth]. Therefore, the estimated lower odds are likely to be explained from a socio-economic perspective. In fact, 50% of the answers from this region in the survey came from the former LHINs of Hamilton Niagara Haldimand Brant, and Erie St. Clair, both which are among the regions of Ontario with the highest proportion of their population (more than 20%) in the lowest income quintile [@buajitti2018] (Supplementary Table A-7). Interestingly, a disproportionate number of COVID-19 cases and low vaccination rate (under 50%) have been also reported in the South Asian community of Ontario [@anand2022]. These results provide context to the observed differences in vaccination among the Health Regions of the province, showing which equity-deserving and socio-demographic groups in certain regions need to be prioritized in future vaccination strategies. Moreover, these results provide a rationale for future studies that explore how vaccination uptake varies across different minority groups within Ontario and other Canadian provinces.

Additionally, significant higher vaccination odds were identified in the West Health Region when compared to the Health Region of Toronto (@fig-model-corr). The West Health Region comprises the regions of Waterloo and Niagara, the counties of Wellington, Essex and Lambton, and the cities of Hamilton, Haldimand, Brant, and Chatham-Kent. In this case, these results could reflect the fact that in the survey, about half of the entries for this Health Region corresponded to White/Caucasian individuals, who reported a vaccination rate of 83\% (Supplementary Table A-6). However, the interaction effect of Health Region and race was also significant in the case of individuals identifying as South Asian or other minorities not included in the survey [@fig-model-corr]. In this case, the results of the interaction term in the model indicate that the odds of vaccination for those within the South Asian and Other minority groups in the West Region decreased when compared to the other Health Regions (Supplementary Figure A-6).

I


From one side, it is important to mention that historically, the social composition of the areas now covered by each Health Region (and previously by the LHINs) has been very different, and 

and we would like to focus on two areas that might help contextualize the observed reduced odds of vaccination. In the case of the West Health Region, 

The rationale behind these results its likely to be dual.

The West Health Region is located in the leftmost southern part of the province, including the regions of Waterloo and Niagara, the counties of Wellington, Essex, and Lambton, and the cities of Hamilton, Haldimand, Brant, and Chatham-Kent. The Central Health Region includes the regions of Peel and Halton, the regional municipality of York, the district of Muskoka, the counties of Dufferin, Simcoe, Grey, and the city of Etobicoke.


According to Ontario Health, 13.2% of the population in the West Health Region identifies as a visible minority, whereas 2.5% identifies as Indigenous [@ontariohealth]. Therefore, the estimated lower odds are likely to be explained from a socio-economic perspective. In fact, 50% of the answers from this region in the survey came from the former LHINs of Hamilton Niagara Haldimand Brant, and Erie St. Clair, both which are among the regions of Ontario with the highest proportion of their population (more than 20%) in the lowest income quintile [@buajitti2018] (Supplementary Table A-7). Interestingly, a disproportionate number of COVID-19 cases and low vaccination rate (under 50%) have been also reported in the South Asian community of Ontario [@anand2022]. These results provide context to the observed differences in vaccination among the Health Regions of the province, showing which equity-deserving and socio-demographic groups in certain regions need to be prioritized in future vaccination strategies. Moreover, these results provide a rationale for future studies that explore how vaccination uptake varies across different minority groups within Ontario and other Canadian provinces.

There are some limitations to the present study. First, the data collection design, which allowed respondents to withdraw from the survey at any point, resulted in a high number of unique entries in the survey with multiple missing answers. Because we focused on entries that had complete observations in the covariates of interest for our analysis, it is possible that some information was not considered by excluding observations that had information in other variables (such as work from home, or number of persons in the household). However, we attempted to minimize this possibility by correcting the dataset using information from the Census. More granular corrections, which for example could be based on demographic information by municipality, could be used in the future to obtain a more accurate approximation to the population totals of the province. Moreover, our analysis did not consider the North West and North East Health Regions, due to the low number of entries from these areas in the survey (@fig-map). Although low representation from these areas is based on the fact that these regions only account for 5\% of the total population of Ontario, these regions are the home to more than 100,000 individuals that identify as Indigenous [@ontariohealth], a minority group that has historically suffered from reduced access to health care and discrimination [@mosby2021]. Therefore, there is a need for additional studies that focus on these low-populated Health Regions in Ontario where disparities in vaccination might be significant and understudied.

It is also worth mentioning that province-wide vaccination rates for the period of interest are somewhat different from those of the survey, particularly in the case of those 55 years of age and older, which in the survey had a vaccination rate of 72\%, against a rate of 88.4\% reported for the closest age bracket (50 years of age and older) reported by Public Health Ontario at the start of the period covered by the data [@ontario-covid]. However, we found good agreement between the estimates from the model and overall vaccination rates reported for Canada, which have been relatively higher when compared to other high income countries [@dube2022], and with vaccination uptake rates across different age groups presented in other studies [@macdonald2021;@guay2022]. 

In other words, although vaccination rates obtained from the survey were slightly lower than the provincial estimates, these values still represented a valid approximation to overall trends; this notion is reinforced by the consistency in the proportion of vaccination rates (@tbl-descriptive-stats) and vaccination odds (@fig-model-corr) across the period covered by the survey, which closely match the vaccination rates from Public Health Ontario and which indicate that due to the relatively high coverage achieved in the population at that point, vaccination rates increased by around 3% across all age groups during the three months covered by the survey [@ontario-covid]. It is also important to mention that to this day, differences in vaccination rates within the province continue. As of March of 2023 some regions still have less than 75\% vaccination rate [@ontario-covid-map], and although data for the period analyzed in this study is not publicly-available, it is likely that differences in vaccination rates were higher at the time, being partially captured by the survey.

The results in this study are based on self-reported data, where bias might be present. However, because in the context of COVID-19 it has been shown that good agreement exists between self-reported and documented vaccination status [@stephenson2022], we believe that our data was able to provide a valid assessment of vaccination in the province. Finally, this study focused on first-dose vaccination status  within a relatively short time window, and therefore can only provide a snapshot of the societal dynamics behind the pandemic. Nonetheless, the results presented here can serve as a starting point to motivate the collection of robust longitudinal data that can be used to quantify geographical and temporal differences within vulnerable segments of the population, and that can be used to inform the development of adequate public health policies within the province of Ontario or across other provinces that aim to minimize disparities in health access.
