# Conclusion

The implementation of the Health Regions in Ontario aimed at reducing the bureaucratic complexity and health disparities identified under the LHIN model. However, there are currently multiple challenges that need to be addressed to ensure that the new model can improve healthcare for the inhabitants of the province. First, the fact that each Health Region now covers a large geographical area that was served by multiple LHINs in the past creates a complex socio-demographic landscape that is different in each case due the different levels of rurality and representation of equity-deserving groups that are now within each Health Region. So far, the evidence collected during the COVID-19 pandemic indicates that differences in vaccination uptake are associated to a lack of infrastructure and resources that can adequately support personalized care to marginalized individuals. In the near future, health decision-makers will need to consider the implementation of policies that are focused on addressing this problematic.

Moreover, the recent nature in the adaption of the Health Region poses a challenge for researchers in the acquisition of data and information that can be used to analyze the performance of the new model. From one side, the Health Regions have not been incorporated as part of Census data (LHINs were considered before in the Census), and this impact the amount and level of detail of available information. On the other hand, evaluations of the Health Region model are at the moment not considered in the Annual Reports of the Auditor General of Ontario, which was critical in the past to identify limitations in the LHIN model. Currently, the only demographic information available for each Health Region is provided by Ontario Health (the agency that administers the Health Regions) but this information only provides general estimates that do not allow for detailed analyses of performance indicators (such as hospitalizations, readmissions, and trends in chronic disease incidence) between the Regions. Therefore, there is a pressing need for open data that can be used by researchers and decision-makers to examine the performance of the Health Region model.

The Health Region model will only by successful if it ensures that healthcare improves across all segments of the population of Ontario, particularly in the event of a future public health emergency or pandemic where so far, based on the experience of the COVID-19 pandemic, underrepresented individuals have been disproportionately affected.