# Background

As of May of 2023, there have been 765 million confirmed cases of COVID-19 around the world, including 6.8 million deaths [@WHO-Covid]. Although this disease is no longer categorized as a global health emergency by the World Health Organization (WHO) [@rigby2023], there is ongoing concern due to continued transmission, the possibility of surges in cases and deaths due to new virus variants [@un2023], and ongoing issues in health systems around the world that could be exploited by a novel virus or another public health emergency in the future [@mackey2021].

In particular, the pandemic showed multiple challenges with regard to vaccination. The rapid development of vaccines against COVID-19 initially brought the hope of a rapid end to the pandemic as vaccination campaigns in certain parts of the world started as early as December of 2020 [@thelancet2021;@davis2022;@bogoch2022;@tanne2020]. Although it has been estimated that so far COVID-19 vaccines have been able to prevent millions of deaths worldwide [@watson2022], their implementation has faced multiple challenges across the world. These challenges included the rapid emergence of new virus variants [@li2021], the waning of vaccine protection [@dolgin2021], inequality in vaccine access between high-income and low-income countries [@gerretsen2021;@tamey2022], vaccine hesitancy [@nafilyan2021], and differences in vaccine uptake across the population [@willis2021;@skirrow2022]. More specifically, it is well established that lower vaccination uptake has been observed in individuals within certain underrepresented groups (e.g., Black, Asian, or Indigenous) as well as individuals with socio-economic disadvantages [@willis2021;@skirrow2022;@stoler2021;@khubchandani2021;@guay2022;@muhajarine2021;@hussain2022]. 

Reasons given for this inequality in vaccination uptake have included medical mistrust due to systemic medical racism [@stoler2021;@mosby2021], mistrust in vaccines [@willis2021], and the existence of health misinformation and disinformation [@bogart2021;@mosby2021;@freeman2020]. However, it is important to consider that vaccination uptake can also vary geographically across the administrative or political subdivisions within a country. For example, differences in COVID-19 vaccination rates have been associated with differences in attitudes towards vaccination in administrative areas in New York and Chicago[@malik2020], scarcity of vaccination facilities in areas where underrepresented groups reside in Toronto when the provincial vaccination program started[@bogoch2022], as well as an absence of prioritization of areas inhabited by vulnerable groups in the southeastern region of the US[@nguyen2021]. Other studies have also shown heterogeneity in vaccine uptake within counties in the US [@mollalo2021; @yang2022; @tiu2022; @bhuiyan2022], indicating that accounting for geographical differences in vaccination can help predict patterns of booster uptake in Scottish communities [@wood2022]. Therefore, the study of vaccination uptake across administrative of political areas can be useful to highlight differences that governments or public health agencies might need to address. However, in the case of Canada, there is a limited amount of studies that have analyzed geographical differences in vaccination. Existing studies in this area have focused on differences within certain cities, such as Toronto [@choi2021], or Montréal [@mckinnon2021]), or have explored differences between provinces-at-large [@guay2022], but to our knowledge, there are no studies that analyze differences in vaccination uptake at the intra-provincial level. Such need is specially important in the context of Canada's pandemic response goals, which have been to minimize serious illness and deaths while minimizing societal disruption [@naci2023]. Analyzing differences in vaccination uptake within the provinces can aid to identify inequalities that might exist and that need to be addressed before the advent of another pandemic.

This need is especially important in the case of Ontario, the most populated province of Canada, and which as has a complex healthcare system. Between 2007 and 2019, Ontario managed healthcare access to its inhabitants using 14 intra-provincial divisions called the Local Health Integration Networks (LHINs), which aimed to provide an integrated health system. However, this approach was complex, bureaucratic, resulting in excessive expenditures, disparities in mortality rates, the deterioration of certain performance indicators (such as wait times and hospital readmissions), fragmented electronic health systems, and inequities in health services access [@tsasis2012;@muratov2018;@dong2022;@lysyk2015;@lysyk2016]. With the intent of better organizing and delivering care, in late 2019 the provincial government eliminated the LHINs and incorporated the areas covered by them into six larger Health Regions (North East, North West, Central, Toronto, West, and East), which are managed by a new government agency, Ontario Health (OH) [@dong2022]. 

On the other hand, public health in Ontario is administered by Public Health Ontario (PHO), a government agency established in late 2007 and that is currently composed of 34 Public Health Units (PHUs) that cover the entire geography of the province. Although PHUs were commissioned with leading the distribution of the COVID-19 vaccine within their respective areas [@rotenberg2021], the vaccine rollout occurred with significant interaction between PHO and OH; in many instances both agencies had to work together to organize vaccination clinics, with personnel associated with OH also being actively involved when demand exceeded the capacity of PHO personnel, especially in rural areas [@ashcroft2023]. Indeed, based on the experience of COVID-19, there are ongoing discussions on how OH and PHO will interact in the future, and the challenges that this will entail for the healthcare system of the province [@dion2022].

Therefore, considering the relatively recent adoption of the Health Region model and its alignment with the onset of the COVID-19 pandemic, there is an ongoing need to analyze the existence of geographical disparities in vaccination uptake within the Health Regions and identify the socio-demographic groups that might be affected, as this can serve as an indirect assessment of the state of the implementation of the new model while helping identify ongoing challenges that decision-makers might need to address to ensure the long-term  success of this model and its interaction with PHO, which is specially important considering that previous research has highlighted disparities in the level of activity of each Health Region [@sethuram2023].

Therefore, in this study we wanted to understand if there were differences in COVID-19 vaccination rates among the Health Regions between October 2021 and January of 2022. To contextualize these differences, we included socio-economic factors in our analysis aiming to identify which demographic groups were particularly impacted, in order to provide an assessment of the current state of healthcare access in Ontario.
