# Discussion

<!-- The COVID-19 pandemic has presented many significant challenges to the healthcare systems of the Canadian provinces [@alami2021]. In the case of Ontario, the recent adoption of the Health Region model at the onset of the pandemic signified an additional level of complexity because although PHO (through the 34 Public Health Units of the province) was the lead in vaccine distribution, in reality the vaccine rollout required active collaboration between PHO and OH in multiple instances [@ashcroft2023].  -->

In this study, we wanted to understand if there were differences in COVID-19 vaccination rates among the Health Regions between October 2021 and January of 2022 while identifying the socio-demographic determinants (and their interactions) that could help predict these differences.
Using the Health Regions as the base of our analysis was advantageous, as these newly implemented administrative areas match closely the geographical boundaries of the Health Regions that have been historically used to group Public Health Units in the province [@bolotin2018;@ohesi]. Thus, a Health Region-based analysis could provide information on vaccination uptake that could be useful to understand patterns within the realm of PHO and OH. Moreover, such analysis could provide an overall assessment of intra-provincial disparities that might need to be addressed moving forward by decision-makers in order to ensure that in the event of a future public health emergency or pandemic, OH and PHO will able to work collaboratively in an efficient way having learned from the COVID-19 experience[@ashcroft2023], thus ensuring that the population of the province benefits in the long term from a robust health system.

Our results show that indeed, there were differences in the uptake of the first dose of the vaccine across Ontario in certain socio-demographic groups. Specifically, those who identified as Arab/Middle Eastern, Black, Latin American, having mixed racial or ethnic background, or that belonged to other groups not explicitly included in the survey (Southeast Asian, Filipino, West Asian, and minority groups not identified elsewhere) had vaccination odds that were between a third and a half of that of individuals that identified as White or Caucasian (@fig-models). These results are consistent with previous studies that have shown lower vaccination rates in individuals with the same socio-demographic characteristics [@guay2022;@muhajarine2021;@carter2022;@hussain2022]. 

Lower vaccine uptake in the socio-demographic groups indicated above may be influenced in part, by vaccine hesitancy and refusal, which have been associated in underrepresented Canadian individuals with concerns on vaccine safety, effectiveness, and experiences of racial discrimination in health settings [@basta2022;@cnat2022a;@cnat2022b;@cnat2023]. However, it has been shown that structural barriers also play an important role in vaccination uptake. In the case of underrepresented individuals, such barriers include complex scheduling systems, language barriers, lack of adequate public transportation, and lack of accessible vaccination sites [@njoku2021]. In this regard, it is interesting to note that vaccination venues were scarce in low socio-economic areas that had the highest burden of COVID-19 in Toronto and other regions of Ontario around the time covered by the survey [@bogoch2022;@iveniuk2021], and that pharmacies in the Peel region (an area identified as a "hotspot" with high numbers of essential workers and multigenerational households) could not keep up with vaccine demand [@gill2022]. This suggests that the observed differences are associated with disparities in vaccine access that were present during the period covered by the survey.

Interestingly, whereas overall self-reported vaccination rates were found to be statistically significantly lower in various underrepresented groups when compared to White/Caucasian individuals, the change in odds of vaccination within certain racial groups and income strata was actually positive, in contrast to the White/Caucasian group, where vaccination odds decreased in income brackets below CAD 60,000 (Supplementary Figure A-5). Specifically, individuals in low income brackets that belonged to Arab/Middle Eastern, Black, or other minority groups had higher odds of vaccination that their peers with an income above 60,000 CAD.

This result likely reflects in part the fact that individuals in underrepresented groups tend to perform occupations that have been deemed as "essential" in the context of the pandemic [@hawkins2020;@ct2021], which include workers in the areas of grocery stores, gas stations, warehouses, distribution, and manufacturing, all being occupations for which an income within the significant brackets identified in the analysis is to be expected. From one side, individuals in essential occupations in the province experienced higher rates of morbidity and mortality during the first year of the pandemic [@rao2021], but later on, they had priority for COVID-19 vaccination [@mishra2021]. Additionally, it is known that vaccination uptake in these individuals was encouraged by vaccination staff in certain parts of the province [@gill2022]. These facts, combined with evidence of increased trends in vaccination in this group elsewhere [@nguyen2021b], suggest that in Ontario, the type of occupation of individuals in underrepresented groups (which might have also affected their decision to get a vaccine based on their knowledge of increased risk), played an important role in the higher the odds of vaccination observed in these individuals.

However, the results also indicate that the place of habitation affected the odds of vaccination for certain underrepresented groups (interaction term of Health Region and Race, @fig-models,B). Specifically, this held true in the case of individuals identifying as Indigenous or with mixed racial background in the West Health Region, Black individuals in the Central Health Region, and Arab/Middle Eastern individuals in the East Health Region [@fig-models]. For these individuals, vaccination odds were lower when compared to the Toronto Health Region (Supplementary Figure A-6). We indicate next some contributing factors that might help provide context to these results.

First, in this case it is useful to analyze the data considering the LHINs in each Health Region, because most studies in the literature focused on Ontario use the LHINs as the base of their analyses. The West Health Region covers the area previously occupied by the Hamilton Niagara Haldimand Brant, South West, and Waterloo Wellington LHINs, whereas the East Health Region covers the area of the former Champlain and Central East LHINs. Previous research has identified health disparities in these (mostly rural) regions, such as unequal distribution of primary care providers, increased mortality, and low pharmacist availability [@shah2019;@crighton2015;@timony2022].

Furthermore, there is an ongoing challenge for the health system of the province with regard to personalized healthcare for marginalized individuals. Indeed, previous studies have pointed out mistrust in the traditional healthcare system (due to systemic racism or oppression) as a rationale for lower vaccination rates in the case of Indigenous and Black individuals in Canada [@smylie2022;@eissa2021]. Other studies have also shown a need for increased culturally responsive care for other underrepresented groups such as Black women and and other immigrant groups in Canada and Ontario [@etowa2021;@patel2019]. Considering that for example, the West Health Region has only two Aboriginal Health Access Centres (community-led primary healthcare organizations focused on First Nations, Métis, and Inuit communities) to provide care to an estimated population of 100,000 Indigenous individuals living in the area [@ontariohealth], it is possible that the limited personalized healthcare for underrepresented groups in certain parts of the province impacted vaccination uptake as well, and highlights the need of investments in the Health Regions focused on resources, infrastructure, and specially personnel that can deliver personalized care to marginalized communities, as it has been shown that such efforts have improved trust in vaccination in underrepresented groups elsewhere [@schafferderoo2020].



There are some limitations to the present study. First, the data collection design, which allowed respondents to withdraw from the survey at any point, and that deployed the questions in a random manner resulted in an elevated number of missing observations without a definite pattern and complicated the implementation of sensitivity analyses. Therefore, we focused on entries that had complete answers, and corrected the data using population-wide information from the Census. However, more granular corrections would be needed to obtain more accurate estimates: For example, our analysis identified higher odds of vaccination in the Central and West Health Regions, but in this case these differences are likely to be driven by the proportion of White/Caucasian individuals, who had higher vaccination rates than other racial groups. Correcting for each racial/ethnic group in each Health Region would provide a more accurate estimation of region-wide vaccination rates but unfortunately, presently this correction cannot be implemented as such stratification has not been implemented in the open data that can be obtained from the Census.

Additionally, our analysis did not consider the North West and North East Health Regions, due to the low number of entries from these areas in the survey (@fig-map). Low representation is expected as these regions as they only account for 5\% of the total population of Ontario. However, these areas have the highest proportion of Indigenous inhabitants [@ontariohealth]. In the context of personalized care, there is a need to collect data that focuses on these Health Regions where additional health disparities might be present and possibly understudied.

The results in this study are based on self-reported data, where bias might be present. However, in the context of COVID-19, it has been shown that good agreement exists between self-reported and documented vaccination status [@stephenson2022], we believe that our data was able to provide a valid sample of vaccination uptake in the province. This is supported by the statistically significant higher vaccination odds that were identified for January of 2022 in the model, which are consistent with province-wide trends reported by Public Health Ontario (which show a 4\% increase between early December and January, in contrast to a 2.5\% increase between October and November [@ontario-covid]); however, the short time window constitutes essentially a "snapshot" view of the evolution of the disease, and additional data would be needed to obtain estimates per racial/ethnic group over time across all Health Regions that can help inform the existence of other health disparities. 

Nonetheless, the results presented here can serve as a starting point to motivate the collection of robust longitudinal data that can be used to quantify geographical and temporal differences within vulnerable segments of the population, and that can be used to inform the development of adequate public health policies within the province of Ontario or across other provinces in Canada that aim to minimize disparities in health access.
