# Conclusion

The evidence collected in this study shows that differences in the uptake of the first dose of the COVID-19 vaccine by underrepresented individuals in the province of Ontario were the result of complex relationships between infrastructure, resources, occupations, geography, and socio-economic factors. Specifically, we identified that between the last trimester of 2021 and January of 2022 individuals that identified as Arab or Middle Eastern, Black, Latin American, of a mixed background, or that belonged to other racial groups had significantly lower odds of vaccination when compared to White/Caucasian individuals in Ontario.

However, although overall vaccination uptake was lower in these underrepresented individuals in the province as a whole, the odds of vaccination differed within certain income levels and Health Regions in these groups, specially for those that reported a low household income and that had higher vaccination odds that individuals in the same racial/ethnic group with a higher income. These results highlight the complex landscape of the province, where varying degrees of rurality exist in conjunction with a socio-demographic makeup that is unique to each of the Health Regions. 

Such complexity presents an ongoing challenge for the healthcare system of Ontario, and in particular, to the Health Region model which will need to adapt and build on the LHIN model with the aim of providing an integrative approach that can serve those that are most vulnerable across all the Health Regions of the province. In particular, personalized care is an area that could be further developed to improve vaccination uptake in underrepresented individuals in the future. As we have shown above, there are currently a limited number of centers focused on community-led healthcare in the province, and our results showed the existence of differences in vaccination uptake between certain Health Regions. Improving personalized care for underrepresented individuals then, can serve as a point to improve trust and facilitate vaccine access in these marginalized communities.

<!-- The implementation of the Health Regions in Ontario aimed at reducing the bureaucratic complexity and health disparities identified under the LHIN model. However, there are certain challenges that this new model will need to overcome in order to work syngergistically with the rest of the healthcare system of the province. First, each Health Region now covers a large geographical area that was served in the past by multiple LHINs. This in turn creates a complex socio-demographic landscape within each Health Region that is likely to be different in each case due the different levels of rurality and the proportion of underrepresented groups in each Health Region.  -->

Furthermore, in the event of a future pandemic or public health emergency in the province in the years ahead, PHO and OH will need to collaborate on the implementation of public health measures (such as vaccination campaigns) building on the experience gained during the COVID-19 vaccination rollout. So far, the COVID-19 pandemic served as a stress test for both agencies, showing the necessity from decision makers to clearly define how PHO and OH will interact in the future in order to ensure that Ontarians can benefit by virtue of a robust collaboration between both agencies. 

<!-- The evidence collected in this study shows that healthcare disparities experienced by underrepresented individuals in the province are the result of complex relationships between infrastructure, resources, occupations, geography, and socio-economic factors, among others. Therefore, this complexity presents an ongoing challenge for the healthcare system of Ontario, which will need to adapt and continue to aim for an integrative approach that can serve those that are most vulnerable. -->


<!-- So far, the evidence collected during the COVID-19 pandemic indicates that differences in vaccination uptake are associated to a lack of infrastructure and resources that can adequately support personalized care to marginalized individuals. In the near future, health decision-makers will need to consider the implementation of policies that are focused on addressing this problematic. -->

Finally, the recent nature in the adaption of the Health Region poses a challenge for researchers in the acquisition of data and information that can be used to analyze the performance of the new model. From one side, the Health Regions have not been incorporated as part of Census data (LHINs were considered before in the Census), and this impacts the amount of data that can be obtained. On the other hand, evaluations of the Health Region model are at the moment not considered in the Annual Reports of the Auditor General of Ontario, which was critical in the past to identify limitations in the LHIN model. Currently, the only demographic information available for each Health Region is provided by Ontario Health (the agency that administers the Health Regions) but this information only provides general estimates that do not allow for detailed analyses of performance indicators (such as hospitalizations, readmissions, and trends in chronic disease incidence) between the Regions. Therefore, there is a pressing need for open data that can be used by researchers and decision-makers to assess the performance of the Health Region model.

<!-- The Health Region model will only by successful if it ensures that healthcare improves across all segments of the population of Ontario, particularly in the event of a future public health emergency or pandemic where so far, based on the experience of the COVID-19 pandemic, underrepresented individuals have been disproportionately affected. -->